name: rainforest_biz_project1
description: ''
version: '0.1'
author: sabu.varghese@point32health.org
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: rainforestbizproject1
  parentArtefactID: sabuvarghesepoint32healthorgteam
  buildSystem: wheel
  author: null
  createdAt: '2024-05-14 01:54:00'
pipelines:
  pipelines/enrich_accounts:
    name: enrich_accounts
    description: ''
    author: sabu.varghese@point32health.org
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-05-14 01:54:00'
    datasets:
      inputs:
      - gitUri=http://gitserver:3000/wvwrv9bI_team_5938/wvwrv9bI_project_13587.git&subPath=&tag=course_lab_sources/0.0.3&projectSubscriptionProjectId=13587&path=datasets/salesforce-Account
      - gitUri=http://gitserver:3000/wvwrv9bI_team_5938/wvwrv9bI_project_13587.git&subPath=&tag=course_lab_sources/0.0.3&projectSubscriptionProjectId=13587&path=datasets/salesforce-Opportunity
      outputs:
      - datasets/enriched_accounts
    subgraphs: []
    dependencies: {}
datasets:
  datasets/enriched_accounts:
    name: enriched_accounts
    description: ''
    author: sabu.varghese@point32health.org
    createdAt: '2024-05-14 02:20:12'
    mode: batch
    physicalDatasets:
      workshop-fabric:
        fabricId: 12311
        datasetType: Database
        description: ''
        author: sabu.varghese@point32health.org
        createdAt: '2024-05-14 02:20:12'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-05-14 01:54:00'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-05-14T01:54:00.116122Z'
  name: plibMaven
  version: 7.1.95
  id: '565020840'
  createdAt: '2024-05-14T01:54:00.116122Z'
  type: plibMaven
- modifiedAt: '2024-05-14T01:54:00.116122Z'
  name: plibPypi
  version: 1.8.15
  id: '76979096'
  createdAt: '2024-05-14T01:54:00.116122Z'
  type: plibPypi
projectDependencies:
  '13587':
    projectUID: 13587
    projectName: course_lab_sources
    repositoryPath: gitUri=http://gitserver:3000/wvwrv9bI_team_5938/wvwrv9bI_project_13587.git&subPath=
    version: course_lab_sources/0.0.3
    isDefault: false
    author: null
    createdAt: '2024-05-14 01:52:07'
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.12
    isDefault: true
    author: null
    createdAt: '2024-05-14 01:52:07'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.5
    isDefault: true
    author: null
    createdAt: '2024-05-14 01:52:07'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
